### ISSUE TITLE
Basket Server

### ISSUE THREAD

**Issue by this-kramer** [upbcuk/incentive-services#7]
We need to mimic the behavior of the basket server in order to prototype the incentive system.  We ignore the rewards at this point to keep complexity low. Later, endpoints for creating, editing, querying, ... rewards could be incorporated.

We have the following use-cases for the basket server.
 - Users initialize a basket
 - Users add a product to their basket
 - Users remove a product from their basket
 - Users query their basket's content
 - Users pay for the items in their basket
 - Users use their paid basket to get a reward (credit-earn-protocol)

Furthermore, we have the following requirements for the basket server:
 - Users should only be able to see and edit their own baskets
 - A basket can be used only once for getting a reward
 - Users should be able to retry getting their reward in case something went wrong
 - The payment should be verified 

Hence, we need the following API endpoints:
 - A verified but anonymous endpoint for users to initialize, edit, and query the basket. 
 - An authenticated endpoint for cash registers and stores to validate the basket contents and perform the payment. (Ensure user does not add anything during the payment process)
 - An authenticated endpoint for the incentive system to validate credit-earn requests and mark baskets as redeemed.

Ideas for this:
 - Users get a token to authenticate to the basket server when they create a basket.
 - Cash registers and incentive services use TLS certificates to authenticate.
 - We use TLS to encrypt all traffic

**Comment by JanBobolz** [comment]
Sounds good. 

Brief remark on our vision security stuff (consider those, but there may be reasons to deviate) - a few simplification suggestions:

- user-access to the basket could be granted simply by the user knowing the basket's id (and then we'd just make basket IDs UUIDs, so they're hard to guess and no user can every guess another user's basket id). No need for dedicated access tokens other than that.
- TLS certificates for two-way authentication are nice, but, I feel, overkill. We control the whole in-store system, so we can just give the basket server, cash registers and incentive servers pairwise shared secrets. Then authentication boils down to a [```Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l```](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) header (or something). No need for generating tls certificates, etc.

**Comment by this-kramer** [comment]
> Sounds good.
> 
> Brief remark on our vision security stuff (consider those, but there may be reasons to deviate) - a few simplification suggestions:
> 
> * user-access to the basket could be granted simply by the user knowing the basket's id (and then we'd just make basket IDs UUIDs, so they're hard to guess and no user can every guess another user's basket id). No need for dedicated access tokens other than that.
> * TLS certificates for two-way authentication are nice, but, I feel, overkill. We control the whole in-store system, so we can just give the basket server, cash registers and incentive servers pairwise shared secrets. Then authentication boils down to a [`Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) header (or something). No need for generating tls certificates, etc.

Good points!

I thought about using UUIDs for the user, my only argument against this would be not trusting the cash systems (by knowing the UUID they could add/remove items to/from the basket). If this is not a problem for us, I would definitely choose this approach.

Shared secrets sound also good to me, too. This would reduce the need for  TLS certificates to the user requests, correct? :+1:

**Comment by JanBobolz** [comment]
> I thought about using UUIDs for the user, my only argument against this was not trusting the cash systems (by knowing the UUID they could add/remove items to/from the basket). If this is not a problem for us, I would definitely choose this approach.

I have no problem with this - it's probably even a feature that the cash register people can add or remove erroneous items from users' baskets. 

> Shared secrets sound also good to me, too. This would reduce the need for TLS certificates to the user requests, correct? 👍

I guess in practice, each server would still need a TLS certificate for establishing a secure connection (we don't want eavesdroppers), it's just that we get rid of the overhead of making tls do mutual authentication. That is: for any given request, the server authenticates to the client via TLS cert, but the client doesn't need a TLS cert, but sends a preshared secret over the encrypted connection.
This "just" reduces the need to do deep/arcane TLS configuration to enable mutual authentication.

**Comment by this-kramer** [comment]
Draft for API model:

```
Item: {
  id: UUID,
  title: string,
  price: int,
}

Basket: {
  id: UUID,
  paid: boolean,
  redeemed: boolean,
  redeemRequest: string,
  value: int,
  items: [
    { 
      item: Item,   # or itemId?
      count: int,
    },
  ],
  stateHash: string
}
```

API calls (use header for UUID in GET requests):
```
basket/new:GET() -> (basketId: UUID),
basket:GET: (basketId: UUID) - > (basket: Basket),
basket:DELETE: (basketId: UUID) -> (),
basket/items:PUT:(basketId: UUID, itemId: UUID, count: int) -> (),
basket/items:DELETE:(basketId: UUID, itemId: UUID) -> (),
basket/pay:POST(basketId: UUID, basketHash: string, value: int) -> (),   # Incentive System / Cash Systems only
basket/pay:GET(basketId: UUID) -> (paid: boolean),
basket/redeem:GET(basketId: UUID) -> (redeemed: boolean, redeemAmount: int, redeemRequest: string),
basket/redeem:POST(basketId: UUID, redeemRequest: string) -> (),   # Incentive System only
 ```

**Comment by this-kramer** [comment]
### Simple first model:
Once a basket is paid, one can redeem the basket's value as a reward. This can later be extended to some other redeeming value or reward type.
